---
version: "3.8"
services:
  dashy:
    image: lissy93/dashy:v3.x
    container_name: dashy
    volumes:
      - ~/.dashy/conf.yml:/app/user-data/conf.yml
    ports:
      - 4000:8080
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
