---
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - ~/.dashy/conf.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
