# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule {
  name = windowrule-1
  workspace = 1
  match:class = ^(Code)$
}

windowrule {
  name = windowrule-2
  workspace = 2
  match:class = ^(Brave-browser)$
}

windowrule {
  name = windowrule-3
  workspace = 4
  match:class = ^(kitty)$
}

windowrule {
  name = windowrule-4
  workspace = 5
  match:class = ^(Slack)$
}


# Browser Picture in Picture
windowrule {
  name = windowrule-5
  float = on
  pin = on
  move = ((monitor_w*0.695)) ((monitor_h*0.04))
  match:title = ^(Picture-in-Picture)$
}


# idleinhibit
windowrule {
  name = windowrule-6
  idle_inhibit = fullscreen
  fullscreen = on
  match:class = ([window]) # Available modes: none
}


# floating windows
windowrule {
  name = windowrule-7
  float = on
  center = on
  size = 900 600
  match:class = ^(org.pulseaudio.pavucontrol)$
}


windowrule {
  name = windowrule-8
  float = on
  center = on
  size = 900 600
  match:class = ^(blueman-manager)$
}


windowrule {
  name = windowrule-9
  float = on
  center = on
  size = 900 600
  match:class = ^(nm-connection-editor)$
}
