#!/bin/bash

SSH_AUTH_SOCK=/run/user/1000/keyring/ssh

# Set external monitor to second connected monitor
BUILD_IN_MONITOR=eDP-1
EXTERNAL_MONITOR=$(xrandr | grep -w connected | awk 'NR==2{print $1}')

if [[ -n $EXTERNAL_MONITOR ]]; then
    xrandr --output $BUILD_IN_MONITOR --mode 1920x1200 --rotate normal --output $EXTERNAL_MONITOR --primary --right-of $BUILD_IN_MONITOR
    bspc wm -O $EXTERNAL_MONITOR $BUILD_IN_MONITOR
    bspc monitor $EXTERNAL_MONITOR -d 1 2 3 4 5
    bspc monitor $BUILD_IN_MONITOR -d 6 7 8 9 10
else
    xrandr --output $BUILD_IN_MONITOR --primary --mode 1920x1200 --rotate normal
    bspc wm -O $BUILD_IN_MONITOR
    bspc monitor $BUILD_IN_MONITOR -d 1 2 3 4 5 6 7 8 9 10
fi

# Launch Polybar
bash ~/.config/polybar/colorblocks/launch.sh
picom -b
 
xsetroot -cursor_name left_ptr
sxhkd &

bspc config border_width	1
bspc config window_gap		15
bspc config border_radius   15

bspc config split_ratio		0.5
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral

bspc config normal_border_color "#44475a"
bspc config active_border_color "#50fa7b"
bspc config focused_border_color "#50fa7b"
bspc config presel_feedback_color "#6272a4"

# Set Background
feh --bg-fill ~/Pictures/Wallpapers/wallpaper.jpeg

# Dekstop Rules
bspc rule -a notion-snap desktop=3
bspc rule -a Slack desktop=5
bspc rule -a kitty desktop=4
bspc rule -a Code desktop=^1

# Start autostart script
bash ~/.config/bspwm/autostart
