#!/bin/bash

bspc wm -O DP-3 eDP-1

bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 0
 
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width	0
bspc config window_gap		20
bspc config border_radius   15

bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral

bspc rule -a slack desktop=0

# Set Background
feh --bg-center ~/Pictures/Wallpapers/wallpaper.jpeg

# Launch Polybar
bash ~/.config/polybar/launch.sh --colorblocks
picom -b

# Dekstop Rules
bspc rule -a Slack desktop=5
bspc rule -a kitty desktop=4
bspc rule -a Code desktop=^1
